### PR TITLE
Fix scaleway_ip ip address attribute read

### PR DESCRIPTION
**Pull request by micktwomey**
The ip attribute wasn't being updated correctly, fixed to read the address from the IP.

### CODE REVIEW

**Comment by moul** [comment]
LGTM

**Comment by arianvp** [comment]
@micktwomey thanks. this is very much a WIP project.

Haven't had much time last few weeks to work on it but I hope to get back to it soon.  If you are feeling like you could help out I can add you to the contributors list. =)

**Comment by arianvp** [comment]
Same counts for you, @moul . If you guys at Scaleway feel like helping out with this project, I can add you to the contributor list :) Just let me know!

**Comment by micktwomey** [comment]
@arianvp thanks for the offer, I'm happy to keep submitting PRs (my next port of call is the security groups). This is a side project for me (building a small cluster in Scaleway to host apps for folks learning to program), so I can't promise anything :)

**Comment by arianvp** [comment]
:+1:

**Pull request merged**
